---
title: "week 3"
author: "Lushi Cai"
date: "27 March 2019"
output: html_document
---

```{R}
library(tidyverse)
letters <- read_csv("sample data.txt")

letters
```

```{r}
sources <- letters %>%
  distinct(source) %>%
  rename(label = source)

destinations <- letters %>%
  distinct(destination) %>%
  rename(label = destination)

nodes <- full_join(sources, destinations, by = "label")
nodes <- nodes %>% rowid_to_column("id")
nodes
```

```{r}
per_route <- letters %>%  
  group_by(source, destination) %>%
  summarise(weight = n()) %>%
  ungroup()

edges <- per_route %>% 
  left_join(nodes, by = c("source" = "label")) %>% 
  rename(from = id)

edges <- edges %>% 
  left_join(nodes, by = c("destination" = "label")) %>% 
  rename(to = id)

edges <- select(edges, from, to, weight)
edges
```

```{r}
library(visNetwork)
edges <-data.frame(edges,arrows="to",dashes=TRUE)


visNetwork(nodes, edges)%>%visLayout(randomSeed = 1)%>% 
  visInteraction(navigationButtons = TRUE)%>%
  visOptions(highlightNearest = TRUE,nodesIdSelection = TRUE,manipulation = TRUE)%>%
  visHierarchicalLayout(direction = "RL")%>%  #LR OR default
 # addFontAwesome()
 # visInteraction(dragNodes = FALSE,dragView = FALSE, zoomView = FALSE)%>%   for freeze network
  visConfigure(enabled = TRUE)%>% #knit to html to see the setting
  visLegend(addNodes = nodes)
```

Arrows
```{R}
nodes <- data.frame(id = 1:5, group = c(rep("A", 2), rep("B", 3)))
edges <- data.frame(from = c(2,5,3,3), to = c(1,2,4,2))

visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shape = "square") %>%                        # square for all nodes
  visEdges(arrows ="from:middle") 

```
addFrontAewsome
```{r}
nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
edges <- data.frame(from = c(1,2), to = c(2,3))

visNetwork(nodes, edges, width = "100%") %>%
  visGroups(groupname = "A", shape = "icon", icon = list(code = "f0c0", size = 75)) %>%
  visGroups(groupname = "B", shape = "icon", icon = list(code = "f007", color = "red")) %>%
  visLegend() %>%
  addFontAwesome()
```
